/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PackagesFlyoutRouteImport } from './routes/packages/flyout'
import { Route as PackagesFloatbarRouteImport } from './routes/packages/floatbar'
import { Route as PackagesAccordionRouteImport } from './routes/packages/accordion'
import { Route as DemoStoreRouteImport } from './routes/demo/store'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesFlyoutRoute = PackagesFlyoutRouteImport.update({
  id: '/packages/flyout',
  path: '/packages/flyout',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesFloatbarRoute = PackagesFloatbarRouteImport.update({
  id: '/packages/floatbar',
  path: '/packages/floatbar',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesAccordionRoute = PackagesAccordionRouteImport.update({
  id: '/packages/accordion',
  path: '/packages/accordion',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStoreRoute = DemoStoreRouteImport.update({
  id: '/demo/store',
  path: '/demo/store',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/demo/store': typeof DemoStoreRoute
  '/packages/accordion': typeof PackagesAccordionRoute
  '/packages/floatbar': typeof PackagesFloatbarRoute
  '/packages/flyout': typeof PackagesFlyoutRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/demo/store': typeof DemoStoreRoute
  '/packages/accordion': typeof PackagesAccordionRoute
  '/packages/floatbar': typeof PackagesFloatbarRoute
  '/packages/flyout': typeof PackagesFlyoutRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/demo/store': typeof DemoStoreRoute
  '/packages/accordion': typeof PackagesAccordionRoute
  '/packages/floatbar': typeof PackagesFloatbarRoute
  '/packages/flyout': typeof PackagesFlyoutRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/demo/store'
    | '/packages/accordion'
    | '/packages/floatbar'
    | '/packages/flyout'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/demo/store'
    | '/packages/accordion'
    | '/packages/floatbar'
    | '/packages/flyout'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/demo/store'
    | '/packages/accordion'
    | '/packages/floatbar'
    | '/packages/flyout'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DemoStoreRoute: typeof DemoStoreRoute
  PackagesAccordionRoute: typeof PackagesAccordionRoute
  PackagesFloatbarRoute: typeof PackagesFloatbarRoute
  PackagesFlyoutRoute: typeof PackagesFlyoutRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages/flyout': {
      id: '/packages/flyout'
      path: '/packages/flyout'
      fullPath: '/packages/flyout'
      preLoaderRoute: typeof PackagesFlyoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages/floatbar': {
      id: '/packages/floatbar'
      path: '/packages/floatbar'
      fullPath: '/packages/floatbar'
      preLoaderRoute: typeof PackagesFloatbarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages/accordion': {
      id: '/packages/accordion'
      path: '/packages/accordion'
      fullPath: '/packages/accordion'
      preLoaderRoute: typeof PackagesAccordionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/store': {
      id: '/demo/store'
      path: '/demo/store'
      fullPath: '/demo/store'
      preLoaderRoute: typeof DemoStoreRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DemoStoreRoute: DemoStoreRoute,
  PackagesAccordionRoute: PackagesAccordionRoute,
  PackagesFloatbarRoute: PackagesFloatbarRoute,
  PackagesFlyoutRoute: PackagesFlyoutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
